In [ ]:
import torch


: 

In [2]:
import torch

# Create sample alpha masks and optic flow tensors
batch_size = 1
N = 2
H = 4
W = 5
alpha_masks = torch.rand(batch_size, N, H, W)
optic_flow = torch.rand(batch_size, N, 2, H, W)

# Element-wise multiply alpha masks and optic flow tensors
masked_optic_flow = torch.mul(alpha_masks[:, :, None, :, :], optic_flow)

# Sum along the second axis (corresponding to the N dimension)
result = torch.sum(masked_optic_flow, dim=1)

print(alpha_masks)


tensor([[[[0.4963, 0.2759, 0.3758, 0.8875, 0.2199],
          [0.3202, 0.7599, 0.5259, 0.4677, 0.5640],
          [0.4305, 0.6116, 0.6129, 0.1376, 0.2845],
          [0.2175, 0.9100, 0.6040, 0.9190, 0.0367]],

         [[0.2446, 0.9548, 0.0243, 0.3759, 0.2940],
          [0.0047, 0.5641, 0.9358, 0.9928, 0.3357],
          [0.9138, 0.1978, 0.2200, 0.4004, 0.4588],
          [0.2163, 0.6384, 0.9682, 0.8029, 0.3227]]]])


In [3]:
print(optic_flow)


tensor([[[[[0.8856, 0.4060, 0.4829, 0.3440, 0.3840],
           [0.6122, 0.4224, 0.0615, 0.0846, 0.7719],
           [0.9120, 0.9590, 0.9448, 0.5211, 0.3415],
           [0.8339, 0.1781, 0.9457, 0.2579, 0.3393]],

          [[0.6769, 0.4266, 0.2729, 0.9596, 0.2128],
           [0.7516, 0.5012, 0.1979, 0.6507, 0.6002],
           [0.7527, 0.8575, 0.4613, 0.2216, 0.9076],
           [0.0687, 0.1193, 0.8417, 0.0682, 0.6081]]],


         [[[0.2527, 0.6347, 0.5653, 0.4942, 0.3779],
           [0.8879, 0.4592, 0.4274, 0.9872, 0.7496],
           [0.8440, 0.7022, 0.0208, 0.7983, 0.2531],
           [0.0117, 0.7993, 0.0673, 0.1947, 0.2727]],

          [[0.4098, 0.8266, 0.4844, 0.5917, 0.2095],
           [0.3216, 0.6751, 0.3358, 0.3081, 0.5339],
           [0.0650, 0.1465, 0.1677, 0.9484, 0.8812],
           [0.7920, 0.7748, 0.9251, 0.9074, 0.3668]]]]])


In [4]:
print(masked_optic_flow)

tensor([[[[[0.4396, 0.1120, 0.1815, 0.3053, 0.0845],
           [0.1960, 0.3210, 0.0323, 0.0395, 0.4353],
           [0.3926, 0.5865, 0.5791, 0.0717, 0.0971],
           [0.1813, 0.1620, 0.5712, 0.2370, 0.0125]],

          [[0.3360, 0.1177, 0.1025, 0.8516, 0.0468],
           [0.2406, 0.3809, 0.1041, 0.3043, 0.3385],
           [0.3240, 0.5244, 0.2827, 0.0305, 0.2582],
           [0.0149, 0.1086, 0.5084, 0.0627, 0.0223]]],


         [[[0.0618, 0.6060, 0.0137, 0.1858, 0.1111],
           [0.0042, 0.2591, 0.4000, 0.9801, 0.2517],
           [0.7713, 0.1389, 0.0046, 0.3197, 0.1161],
           [0.0025, 0.5102, 0.0652, 0.1563, 0.0880]],

          [[0.1002, 0.7893, 0.0118, 0.2224, 0.0616],
           [0.0015, 0.3808, 0.3142, 0.3058, 0.1793],
           [0.0594, 0.0290, 0.0369, 0.3798, 0.4043],
           [0.1713, 0.4946, 0.8957, 0.7286, 0.1184]]]]])


In [5]:
print(result)

tensor([[[[0.5014, 0.7180, 0.1952, 0.4911, 0.1956],
          [0.2002, 0.5800, 0.4323, 1.0197, 0.6870],
          [1.1639, 0.7254, 0.5837, 0.3913, 0.2133],
          [0.1839, 0.6722, 0.6364, 0.3933, 0.1005]],

         [[0.4362, 0.9070, 0.1143, 1.0740, 0.1084],
          [0.2422, 0.7617, 0.4183, 0.6101, 0.5177],
          [0.3834, 0.5534, 0.3196, 0.4102, 0.6625],
          [0.1862, 0.6032, 1.4041, 0.7912, 0.1407]]]])


In [9]:
result2 = (optic_flow * alpha_masks[:, :, None, :, :]).sum(1)



print(result == result2)

tensor([[[[True, True, True, True, True],
          [True, True, True, True, True],
          [True, True, True, True, True],
          [True, True, True, True, True]],

         [[True, True, True, True, True],
          [True, True, True, True, True],
          [True, True, True, True, True],
          [True, True, True, True, True]]]])


In [18]:
import torch
from tqdm import tqdm

def get_optical_flow(A, flow_list, coords):
    """
    Calculates estimated optical flow for a given motion model A
    Input: A: [batch_size x N_classes x 2 x 3]   2x3   (1,x,y)x1
           flow_list: [batch_size x N_classes x 2 x H x W ] list of optical flow (x, y) maps
    Output: flow: batch_size x N_classes x 2 x H x W ]tensor of estimated optical flow
    """
    
    for b in range(A.shape[0]): # B
        for n in range(A.shape[1]): # N_classes  
            flow_list[b,n, :, :, :] = torch.matmul(A[b,n,:], coords.view(3, -1)).view(2, flow_list.shape[3], flow_list.shape[4])
    return flow_list

def get_optical_flow_old(A, flow_list):
    """
    Calculates estimated optical flow for a given motion model A
    Input: A: [batch_size x N_classes x 2 x 3]   2x3   (1,x,y)x1
           flow_list: [batch_size x N_classes x 2 x H x W ] list of optical flow (x, y) maps
    Output: flow: batch_size x N_classes x 2 x H x W ]tensor of estimated optical flow
    """
    B, N_classes, _,  H, W = flow_list.shape
    
    for b in range(A.shape[0]): # B
        for n in range(A.shape[1]): # N_classes
            for h in range(H): 
                for w in range(W):
                    u_x, u_y = torch.matmul(A[b,n,:],torch.tensor([1,h,w], device = A.device, dtype = A.dtype))
                    flow_list[b,n,h,w,0] = u_x
                    flow_list[b,n,h,w,1] = u_y     
            
    return flow_list

ModuleNotFoundError: No module named 'tqdm'

In [2]:
import torch

def get_optical_flow(A, flow_list, coords):
    """
    Calculates estimated optical flow for a given motion model A
    Input: A: [batch_size x N_classes x 2 x 3]   2x3   (1,x,y)x1
           flow_list: [batch_size x N_classes x 2 x H x W ] list of optical flow (x, y) maps
    Output: flow: batch_size x N_classes x 2 x H x W ]tensor of estimated optical flow
    """
    B, N_classes, _, H, W = flow_list.shape
    for b in range(A.shape[0]): # B
        for n in range(A.shape[1]): # N_classes  
            flow_list[b,n, :, :, :] = torch.matmul(A[b,n,:], coords.view(3, -1)).view(2, H, W)
    return flow_list

def get_optical_flow_old(A, flow_list):
    """
    Calculates estimated optical flow for a given motion model A
    Input: A: [batch_size x N_classes x 2 x 3]   2x3   (1,x,y)x1
           flow_list: [batch_size x N_classes x 2 x H x W ] list of optical flow (x, y) maps
    Output: flow: batch_size x N_classes x 2 x H x W ]tensor of estimated optical flow
    """
    B, N_classes, _, H, W = flow_list.shape
    
    for b in range(A.shape[0]): # B
        for n in range(A.shape[1]): # N_classes
            for h in range(H): 
                for w in range(W):
                    u_x, u_y = torch.matmul(A[b,n,:],torch.tensor([1,h,w], device = A.device, dtype = A.dtype))
                    flow_list[b,n,0,h,w] = u_x
                    flow_list[b,n,1,h,w] = u_y     
            
    return flow_list


B = 1
N_classes = 2
H = 4
W = 5
A = torch.rand(1, 2, 2, 3)
flow_list = torch.rand(1, 2, 2, 4, 5)

coords = torch.zeros(3, 4, 5)
coords[0] = 1
coords[1] = torch.arange(H).view(H, 1).repeat(1, W)
coords[2] = torch.arange(W).view(1, W).repeat(H, 1)
flow_1 = get_optical_flow(A, flow_list, coords)
flow_2 = get_optical_flow_old(A, flow_list)
flow_3 = torch.nn.functional.affine_grid(A.view(-1,2,3),
                                              (B*N_classes, 2, H, W)
                                              ).view(B, N_classes, 2, H, W
                                                )
            


/Users/youssef/.pyenv/versions/3.7.13/envs/event_flow/lib/python3.7/site-packages/torch/nn/functional.py:3448: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior has changed "


In [5]:
are_equal_old = torch.all(torch.eq(flow_1, flow_2))
are_equal_affine = torch.all(torch.eq(flow_1, flow_3))

for b in range(B):
    flow_list[b,:,:,:,:] = torch.nn.functional.affine_grid(A[b,:,:,:].view(-1,2,3),(N_classes, 2, H, W)).view(N_classes, 2, H, W)


print(are_equal_old)
print(are_equal_affine)
print(torch.all(torch.eq(flow_1, flow_list)))
print(torch.all(torch.eq(flow_1, flow_list_2)))




ValueError: Expected a batch of 3D affine matrices of shape Nx3x4 for size (1, 2, 2, 4, 5). Got torch.Size([1, 2, 2, 3]).

In [7]:

import torch
H = 3
W = 4


# Create the input tensors of shape (2, H, W)
alpha = torch.randn(2, H, W)

# Compare the two channels element-wise
channel_max = torch.max(alpha, dim=0, keepdim=True)[0]

# Set all other channel to zero
output = torch.where(alpha == channel_max, alpha, torch.zeros_like(alpha))

print(alpha)




tensor([[[ 0.1396,  0.6987,  1.1530, -0.1947],
         [ 0.0175,  0.2124,  0.2099,  0.7877],
         [ 1.5968, -1.2159, -0.6406,  0.5038]],

        [[ 0.6905,  0.1414,  0.8906, -1.7498],
         [-0.3110, -0.4238, -0.4851, -0.1280],
         [-0.1908, -0.6726,  0.2247,  1.2559]]])


In [8]:
print(output)

tensor([[[ 0.0000,  0.6987,  1.1530, -0.1947],
         [ 0.0175,  0.2124,  0.2099,  0.7877],
         [ 1.5968,  0.0000,  0.0000,  0.0000]],

        [[ 0.6905,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000, -0.6726,  0.2247,  1.2559]]])


In [ ]:
import torch

# Create a 100 channel HxW matrix with random values
H, W = 2, 3
channels = 4
matrix = torch.arange(0, 24, step=1,dtype=torch.float64).view(channels,H, W)  # b_tensor expanded to channels


# Create a 1x100 vector with random values
vector = torch.randn(1, channels)   # w_x tensor
# print(vector.expand(H, W, channels))

# Add the vector to each value in the matrix
matrix += vector.expand(H, W, channels).permute(2, 0, 1)
print(matrix)

In [18]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

In [19]:
a = a.expand(2,2,3)
print(a)

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])


In [26]:
x_tensor = torch.tensor([7, 8])


In [28]:
x_tensor = x_tensor.expand(2,3,2).permute(2,0,1)
print(x_tensor)

tensor([[[7, 7, 7],
         [7, 7, 7]],

        [[8, 8, 8],
         [8, 8, 8]]])


In [ ]:
H = 5
W = 6

coords= torch.empty(3,H,W)
    
for h in range(H):
    for w in range(W):
        coords[0,h,w] = 1
        coords[1,h,w] = h
        coords[2,h,w] = w

print(coords)

In [ ]:
kernel = torch.ones((2,3))
kernel[0,:] = 2
result = torch.matmul(kernel, coords.view(3, -1)).view(2, 5, 6)
print(result)

In [ ]:
tensor_sorted, _ = torch.sort(tensor, dim=1)

In [ ]:
print(tensor_sorted)

In [ ]:
tensor_sorted_cat = torch.cat([torch.zeros([2,1,4,5]), -tensor_sorted], dim = 1)
#b_tensor = torch.cumsum(b_tensor,dim = 1)

In [ ]:
print(tensor_sorted_cat)

In [ ]:
b_tensor = torch.cumsum(tensor_sorted_cat,dim = 1)

In [ ]:
print(b_tensor)

In [ ]:
import numpy as np
from PIL import Image
from matplotlib import pyplot as plt
import cv2
from random import randrange 
import time

In [ ]:
# clean memory from figures created using plt.figure in previous sessions

plt.show(block=False); time.sleep(5); plt.close('all')
#plt.get_fignums()

In [ ]:
class Image_Warping():
    
    def __init__(self,image_path = "McS9K.png", N = 1, circle_radius = 25):
        self.path = image_path
        self.N = N
        self.radius = circle_radius
        
        self.plot = True
        self.img, self.image_shape = self.image_loader()
        self.A = self.get_motions_models()
        self.alpha_maps = self.get_alpha_maps()
        self.rgb_layers = self.get_rgb_layers()
        self.flow_x,self.flow_y, self.pixel_x, self.pixel_y = self.get_optical_flow(self.A)
        self.new_pixel_x, self.new_pixel_y = self.get_new_pixels()
        self.warped_rgb_layer = self.get_warped_rgb_layer()
        self.warped_rgb_layers = self.get_warped_layers()
        warped_image = self.get_warped_image()
        
        pass

    def image_loader(self, plot = True):
        '''load image'''
        img = Image.open(self.path)
        img = np.asarray(img).copy()

        image_shape = img.shape
        if plot == True:
            plt.figure()
            plt.imshow(img)
            plt.title("Original Image")
            plt.show()
        
        return img, image_shape

    def get_motions_models(self, round = True, scale = 1):

        '''create N random affine motions'''
        A = np.empty((self.N,2,3))*scale

        for i in range(self.N):
        

            model = np.random.rand(2,3)
            model = np.round(model) if round == True else model
            if self.N == 1:
                A = model
            elif self.N > 1:
                A[i,:,:] = model

        return A 

    def get_alpha_maps(self, plot = True):

        '''create N  alpha maps with shape of a circle'''
        
        R = self.radius
        offset = round(R * 2.1)
        x_lim = self.image_shape[1]/2
        y_lim = self.image_shape[0]/2
        
        x_lim = round(x_lim)
        y_lim = round(y_lim)

        
        alpha_maps = []
        for _ in range(self.N):
            mask = np.zeros(self.image_shape)
            alpha_map = cv2.circle(mask,(randrange(R,x_lim-R, offset),randrange(R,y_lim-R, offset)),R,(1,1,1),-1)
            if self.N == 1:
                alpha_maps = alpha_map    
            elif self.N > 1:
                alpha_maps.append(alpha_map)
                
            if plot == True:
                plt.figure()
                plt.imshow(alpha_map)
                plt.title("Alpha map")
                plt.show()
            
        return alpha_maps

    def get_rgb_layers(self, plot = True):

        '''take alpha maps as input, output rgb layers '''

        rgb_layers = []
        
        for i in range(self.N):
            rgb_layer = self.img.copy()
            
            if self.N == 1:
                rgb_layer[self.alpha_maps == 0] = 0 
                rgb_layers = rgb_layer

            elif self.N > 1:
                rgb_layer[self.alpha_maps[i] == 0] = 0 
                rgb_layers.append(rgb_layer)
            
            if plot:
                plt.figure()
                plt.imshow(rgb_layer)
                plt.title("RGB layer")
                plt.show()

        return rgb_layers
    
    def get_optical_flow(self, A, round = True):

        
        pixel_x, pixel_y = np.where(self.rgb_layers[:,:,0] != 0)
        #print(type(pixel_x),type(pixel_y))
        flow_x = np.zeros((self.rgb_layers.shape[0], self.rgb_layers.shape[1])) 
        flow_y = flow_x

        for i,j in zip(pixel_x,pixel_y):
            
            u_x, u_y = np.matmul(A,np.array([1,i,j]))
            
            flow_x[i,j] = u_x
            flow_y[i,j] = u_y
            
        flow = np.stack((flow_x,flow_y), axis = 0)   # flow_x = flow[0,:,:]; flow_y = flow[1,:,:]


        return flow_x,flow_y, pixel_x, pixel_y

    def get_new_pixels( self, round = True):
        
        new_pixel_x = self.pixel_x + self.flow_x[self.pixel_x,self.pixel_y]
        new_pixel_y = self.pixel_y + self.flow_y[self.pixel_x,self.pixel_y]
        
        new_pixel_x = np.round(new_pixel_x).astype(int) if round == True else new_pixel_x
        new_pixel_y = np.round(new_pixel_y).astype(int) if round == True else new_pixel_y
            
        return new_pixel_x, new_pixel_y 
    
    def get_warped_rgb_layer(self):
        
        warped_rgb_layer = np.zeros_like(self.rgb_layers)
        warped_rgb_layer[self.new_pixel_x,self.new_pixel_y,:] = self.rgb_layers[self.pixel_x,self.pixel_y,:]
        return warped_rgb_layer

    def get_warped_layers(self, plot = True):
        '''take as input the rgb layers, motion models, and alpha maps, output the warped rgb layers'''
        warped_rgb_layers = []
        
        for i in range(self.N):
            if self.N ==1:
                self.flow_x,self.flow_y, self.pixel_x, self.pixel_y = self.get_optical_flow(self.A)
                new_pixel_x, new_pixel_y = self.get_new_pixels()
                warped_rgb_layer = self.get_warped_rgb_layer()
                warped_rgb_layers = warped_rgb_layer
                
            elif self.N > 1:
                flow_x, flow_y, pixel_x, pixel_y = self.get_optical_flow(self.A[i,:,:],self.rgb_layers[i]) 
                new_pixel_x, new_pixel_y = self.get_new_pixels(pixel_x, pixel_y, flow_x, flow_y)
                warped_rgb_layer = self.get_warped_rgb_layer(self.rgb_layers[i], new_pixel_x, new_pixel_y, pixel_x, pixel_y)
                warped_rgb_layers.append(warped_rgb_layer)
            
            if plot:
                plt.figure()
                plt.imshow(warped_rgb_layer)
                plt.title("Warped RGB layer")
                plt.show()

        return warped_rgb_layers
    
    def get_warped_image(self):
        '''take as input the warped rgb layers, output the warped image'''
        warped_image = self.img.copy()
        plt.figure()
        for i in range(self.N):
            if self.N == 1:
                warped_image[self.warped_rgb_layers != 0] = self.warped_rgb_layers[self.warped_rgb_layers != 0]
                break
            elif self.N > 1:
                warped_image[self.warped_rgb_layers[i] != 0] = self.warped_rgb_layers[i][self.warped_rgb_layers[i] != 0]
        plt.imshow(warped_image)
        return warped_image

In [ ]:
if __name__ == "__main__" :

    obj = Image_Warping()
    warped_image = obj.get_warped_image()

In [ ]:

def image_loader(path, plot = True):
    '''
    load image
    '''
    img = Image.open(path)
    img = np.asarray(img).copy()
    image_shape = img.shape
    if plot:
        plt.figure()
        plt.imshow(img)
        plt.title("Original image")
        plt.show()
    return img, image_shape

def get_motions_models(N, round = True, scale = 1):

    '''create N random affine motions'''
    A = np.empty((N,2,3))*scale

    for i in range(N):
    
        model = np.random.rand(2,3)
        model = np.round(model) if round == True else model
        if N == 1:
            A = model
        elif N > 1:
            A[i,:,:] = model

    return A 

def get_alpha_maps(N,image_shape, plot = True):
    ''' create N random alpha maps with shape of a circle'''
    
    radius = 25
    offset = round(radius * 2.1)
    x_lim = image_shape[1]/2
    y_lim = image_shape[0]/2
    
    alpha_maps = []
    for _ in range(N):
        mask = np.zeros(image_shape)
        alpha_map = cv2.circle(mask,(randrange(radius,round(x_lim)-radius, offset),randrange(radius,round(y_lim)-radius, offset)),radius,(1,1,1),-1)
        if N == 1:
            alpha_maps = alpha_map
            
        elif N > 1:
            alpha_maps.append(alpha_map)
        
        if plot:
            plt.figure()
            plt.imshow(alpha_map)
            plt.title("Alpha map")
            plt.show()
         
    return alpha_maps

def get_rgb_layers(N,alpha_maps,img, plot = True):
    '''take alpha maps as input, output rgb layers '''
    rgb_layers = []
    
    for i in range(N):
        rgb_layer = img.copy()
        if N == 1:
            rgb_layer[alpha_maps == 0] = 0 
            rgb_layers = rgb_layer
            
            
        elif N > 1:
            rgb_layer[alpha_maps[i] == 0] = 0 
            rgb_layers.append(rgb_layer)
            plt.figure()
            plt.imshow(rgb_layer)
        
        if plot:
            plt.figure()
            plt.imshow(rgb_layer)
            plt.title("RGB layer")
            plt.show()
        
    return rgb_layers 

def get_optical_flow(A,rgb_layer, round = True):

    '''take as input the motion model and the rgb layer, output optic flow according to that rgb layer'''
    pixel_x, pixel_y = np.where(rgb_layer[:,:,0] != 0)
    flow_x = np.zeros((rgb_layer.shape[0], rgb_layer.shape[1])) 
    flow_y = flow_x
    
    for i,j in zip(pixel_x,pixel_y):
        
        u_x, u_y = np.matmul(A,np.array([1,i,j]))
        
        flow_x[i,j] = u_x
        flow_y[i,j] = u_y
        
    flow = np.stack((flow_x,flow_y), axis = 0)   # flow_x = flow[0,:,:]; flow_y = flow[1,:,:]

    
    return flow_x,flow_y, pixel_x, pixel_y

def get_new_pixels(pixel_x, pixel_y, flow_x, flow_y, round = True):
    '''take as input the pixel coordinates and the flow, output the new pixel coordinates'''
    new_pixel_x = pixel_x + flow_x[pixel_x,pixel_y]
    new_pixel_y = pixel_y + flow_y[pixel_x,pixel_y]
    print(new_pixel_x)
    new_pixel_x = np.round(new_pixel_x).astype(int) if round == True else new_pixel_x
    new_pixel_y = np.round(new_pixel_y).astype(int) if round == True else new_pixel_y
        
    return new_pixel_x, new_pixel_y   

def get_warped_rgb_layer(rgb_layer, new_pixel_x, new_pixel_y, pixel_x, pixel_y):
    '''take as input the rgb layer, new pixel coordinates, and old pixel coordinates, output the warped rgb layer'''
    warped_rgb_layer = np.zeros_like(rgb_layer)
    warped_rgb_layer[new_pixel_x,new_pixel_y,:] = rgb_layer[pixel_x,pixel_y,:]
    return warped_rgb_layer

def get_warped_layers(N, rgb_layers, A, alpha_layers, plot = True):
    '''take as input the rgb layers, motion models, and alpha maps, output the warped rgb layers'''
    warped_rgb_layers = []
    
    for i in range(N):
        if N ==1:
            flow_x,flow_y, pixel_x, pixel_y = get_optical_flow(A,rgb_layers)
            new_pixel_x, new_pixel_y = get_new_pixels(pixel_x, pixel_y, flow_x, flow_y)
            warped_rgb_layer = get_warped_rgb_layer(rgb_layers, new_pixel_x, new_pixel_y, pixel_x, pixel_y)
            warped_rgb_layers = warped_rgb_layer
        elif N > 1:
            flow_x, flow_y, pixel_x, pixel_y = get_optical_flow(A[i,:,:],rgb_layers[i]) 
            new_pixel_x, new_pixel_y = get_new_pixels(pixel_x, pixel_y, flow_x, flow_y)
            warped_rgb_layer = get_warped_rgb_layer(rgb_layers[i], new_pixel_x, new_pixel_y, pixel_x, pixel_y)
            warped_rgb_layers.append(warped_rgb_layer)
            
        if plot:
            plt.figure()
            plt.imshow(warped_rgb_layer)
            plt.title("Warped rgb layer")
            plt.show()
    return warped_rgb_layers

def get_warped_image(N, warped_rgb_layers,img, plot = True):
    '''take as input the warped rgb layers, output the warped image'''
    warped_image = img.copy()
    
    for i in range(N):
        if N == 1:
            warped_image[warped_rgb_layers != 0] = warped_rgb_layers[warped_rgb_layers != 0]
            break
        elif N > 1:
            warped_image[warped_rgb_layers[i] != 0] = warped_rgb_layers[i][warped_rgb_layers[i] != 0]
    if plot:
        plt.figure()
        plt.imshow(warped_image)
        plt.title("Warped image")
        plt.show()   
    return warped_image

In [ ]:
N = 1
img, image_shape = image_loader("image_folder/McS9K.png")
alpha_layers = get_alpha_maps(N, image_shape)
rgb_layers = get_rgb_layers(N,alpha_layers,img.copy())

In [ ]:
A = get_motions_models(N, round = False, scale = 1)

In [ ]:
warped_rgb_layers = get_warped_layers(N, rgb_layers, A, alpha_layers)
warped_image = get_warped_image(N, warped_rgb_layers,img)